version: "1.0.1"

services:
  oi-bot:
    build: .
    container_name: OI-Bot
    ports:
      - "8024:8024"
    env_file:
      - .env   # 这里自动读取 .env 文件中的所有变量
    environment:
      - CLIST__USERNAME=
      - CLIST__USER_KEY=
      - ONEBOT_ACCESS_TOKEN=
    restart: unless-stopped
