services:
  oi-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oi-bot
    restart: unless-stopped
    ports:
      - "8024:8024"
    env_file:
      - .env
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - CLIST__USERNAME=${CLIST__USERNAME}
      - CLIST__USER_KEY=${CLIST__USER_KEY}
      - ONEBOT_ACCESS_TOKEN=${ONEBOT_ACCESS_TOKEN}
    labels:
      createdBy: "talentestors"
    logging:
      driver: "json-file"
      options:
        max-size: "16m"
        max-file: "7"
