name: Monitor Docker Tag and Rename Folder

on:
  schedule:
    - cron:  '0/30 * * * *'
  workflow_dispatch:

jobs:
  update-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 1panel

      - name: Get Docker tag
        id: get_docker_tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repo="talentestors/oi-bot"
          token=$(curl -s "https://ghcr.io/token?service=ghcr.io&scope=repository:${repo}:pull" \
            -u "${{ github.actor }}:${GH_TOKEN}" | jq -r '.token')
          TAG=$(curl -s -H "Authorization: Bearer $token" \
            "https://ghcr.io/v2/${repo}/tags/list" | jq -r '.tags[]' | grep -E '^[0-9]+(\.[0-9]+)+$' | sort -V | tail -n 1)
          echo "Docker tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Check current directory contents
        run: |
          echo "Current directory contents:"
          ls -la /home/runner/work/OI-Bot/OI-Bot

      - name: Get current folder name
        id: get_current_folder
        run: |
          current_folder=$(basename $(ls -d /home/runner/work/OI-Bot/OI-Bot/*/ | head -n 1))
          echo "Current folder name: $current_folder"
          echo "current_folder_name=$current_folder" >> $GITHUB_OUTPUT

      - name: Compare and rename folder
        if: ${{ steps.get_current_folder.outputs.current_folder_name != steps.get_docker_tag.outputs.tag }}
        run: |
          current_folder="/home/runner/work/OI-Bot/OI-Bot/${{ steps.get_current_folder.outputs.current_folder_name }}"
          target_folder="/home/runner/work/OI-Bot/OI-Bot/${{ steps.get_docker_tag.outputs.tag }}"

          echo "Current folder path: $current_folder"
          echo "Target folder path: $target_folder"

          if [ -d "$current_folder" ]; then
            echo "Renaming folder."
            mv "$current_folder" "$target_folder"
            git config --global user.email "talentestors@gmail.com"
            git config --global user.name "talentestors"
            rm -rf .git/
            git init
            git add .
            git commit -m "Rename folder from ${current_folder_name} to ${TAG}"
            git remote add origin https://github.com/talentestors/OI-Bot.git
            git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/talentestors/OI-Bot.git HEAD:refs/heads/1panel
          else
            echo "Source folder '$current_folder' does not exist."
            exit 1
          fi

      - name: Notify if no rename needed
        if: ${{ steps.get_current_folder.outputs.current_folder_name == steps.get_docker_tag.outputs.tag }}
        run: echo "No folder rename needed. Current folder name is already ${TAG}"
